### ISSUE TITLE
Hugo NexT V4 Roadmap

### ISSUE THREAD

**Issue by elkan1788** [hugo-next/hugo-theme-next#9]
## 已实现功能 (Compeleted)

- [x] 保留 4 种不同页面布局模式，完成所有设计迁移
- [x] 实现 SCSS 动态样式迁移及语法和显示问题修复
- [x] 采用 `YAML` 作为配置语法兼容原 `NexT` 参数
- [x] 增加导航菜单动态效果
- [x] 实现代码块高亮功能、行号显示、一键复制及多种样式自定义
- [x] 重新设计文章头部元素的布局为两行
- [x] 重新设计文章版权和关注渠道显示效果
- [x] 底部增加公共资源提供商感谢标语
- [x] 设计评论插件加载效果，同时调整两个评论插件布局与切换效果
- [x] 支持 `Waline` 、`LiveRe`、`Artalk`、`Utterances` 和 `Giscus` 评论插件
- [x] 支持 谷歌 、百度、微软、和 Yandex 站点验证
- [x] 支持 51LA 站点统计
- [x] 基于 `Waline` 的文章访问统计
- [x] 实现指定文章置顶功能
- [x] 实现文章在线编辑链接跳转
- [x] 实现 Github 横幅显示
- [x] 实现全站加载动画效果
- [x] 添加腾讯公益 404 页面
- [x] 支持中、英双语的部署
- [x] 支持 CDN 提供商一键配置
- [x] 关于自己信息介绍页面
- [x] 其他功能优化

## 待实现功能 (Todo)

- [ ] #19
- [ ] #27
- [ ] 文章图片浏览及懒加载
- [ ] 自定义字体设置
- [ ] 自定义脚本、样式设置
- [x] #18
- [ ] 多语言切换功能
- [ ] 深浅主题切换功能
- [x] #26
- [ ] 站点运营数据显示
- [ ] 二级菜单展现
- [ ] #30
- [ ] 文章目录添加有序数字
- [ ] 移动端显示问题修复与优化
- [ ] 阅读更多的锚定跳转
- [ ] 标题的锚定支持
- [x] #12
- [ ] Tab标签卡切换
- [x] #29
- [ ] 多媒体短代码支持
- [ ] 多级分类展现（计划支持最多3层）
- [ ] 主题使用手册撰写

**Comment by elkan1788** [comment]
> 非常好，我最近一直在找静态博客的，试过Jekyll ，Hexo，最后发现hugo的最好，而且next的主题，确实很喜欢

那欢迎多些关注，期待后续使用反馈!

**Comment by elkan1788** [comment]
> 太强了，佬，从2022年到现在，不断地更新，向您致敬

也是感谢很多的`NexT`粉丝支持 😄
